apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_ACCESS_SECRET:  {{ .Values.global.jwtAccessSecret | quote }}
  JWT_REFRESH_SECRET: {{ .Values.global.jwtRefreshSecret | quote }}

  # Database URLs (one per service)
  AUTH_DATABASE_URL:         "postgresql://{{ .Values.auth.db.user }}:{{ .Values.auth.db.password }}@{{ .Values.auth.db.name }}:5432/{{ .Values.auth.db.database }}"
  PRODUCT_DATABASE_URL:      "postgresql://{{ .Values.product.db.user }}:{{ .Values.product.db.password }}@{{ .Values.product.db.name }}:5432/{{ .Values.product.db.database }}"
  CART_DATABASE_URL:         "postgresql://{{ .Values.cart.db.user }}:{{ .Values.cart.db.password }}@{{ .Values.cart.db.name }}:5432/{{ .Values.cart.db.database }}"
  INVENTORY_DATABASE_URL:    "postgresql://{{ .Values.inventory.db.user }}:{{ .Values.inventory.db.password }}@{{ .Values.inventory.db.name }}:5432/{{ .Values.inventory.db.database }}"
  ORDER_DATABASE_URL:        "postgresql://{{ .Values.order.db.user }}:{{ .Values.order.db.password }}@{{ .Values.order.db.name }}:5432/{{ .Values.order.db.database }}"
  PAYMENT_DATABASE_URL:      "postgresql://{{ .Values.payment.db.user }}:{{ .Values.payment.db.password }}@{{ .Values.payment.db.name }}:5432/{{ .Values.payment.db.database }}"
  SHIPPING_DATABASE_URL:     "postgresql://{{ .Values.shipping.db.user }}:{{ .Values.shipping.db.password }}@{{ .Values.shipping.db.name }}:5432/{{ .Values.shipping.db.database }}"
  NOTIFICATION_DATABASE_URL: "postgresql://{{ .Values.notification.db.user }}:{{ .Values.notification.db.password }}@{{ .Values.notification.db.name }}:5432/{{ .Values.notification.db.database }}"
  REVIEWS_DATABASE_URL:      "postgresql://{{ .Values.reviews.db.user }}:{{ .Values.reviews.db.password }}@{{ .Values.reviews.db.name }}:5432/{{ .Values.reviews.db.database }}"
